{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 1, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000178ADB73E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/maincategory (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178ADB73E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/maincategory (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178ADB73E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_getMainCategory", "rerun": "0"}, "1": {"status": "SKIP", "message": "('C:\\\\projects\\\\practice\\\\python\\\\pytest\\\\TestCases\\\\test_createMainCategory.py', 18, 'Skipped: skip')\n", "test_name": "test_createmaincategory", "rerun": "0"}}, "suite_name": "TestCases/test_createMainCategory.py"}, "1": {"suite_name": "TestCases/test_get.py", "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000178AE250050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/maincategory/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178AE250050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/maincategory/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178AE250050>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_getrequest", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000178AE1D24D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/subcategory/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178AE1D24D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n       requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/subcategory/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000178AE1D24D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_getrequest2", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}}}}, "date": "October 30, 2023", "start_time": 1698683342.9104815, "total_suite": 2, "status": "FAIL", "status_list": {"pass": "0", "fail": "3", "skip": "1", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}